# Creates/Resets the gh-pages branch to the intended start state

name: "55-chromatic-pr: Update chromatic for a pr to main"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/55-chromatic-pr.yml

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs: 
  get-pr-num:
    name: Get PR Number
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get-pr-num.outputs.pr_number }}
      branch_name: ${{ steps.get-branch-name.outputs.branch_name }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        token: ${{ github.token }}
    - name: Get PR number
      id: get-pr-num
      run: |
         echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
         pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
         echo "pr_number=${pr_number}" 
         echo "pr_number=${pr_number}" >> "$GITHUB_OUTPUT"
    - name: Figure out Branch name
      id: get-branch-name
      run: | 
          GITHUB_HEAD_REF="${GITHUB_HEAD_REF}"
          echo GITHUB_HEAD_REF=${GITHUB_HEAD_REF}
          GITHUB_REF_CLEANED=${GITHUB_REF/refs\/heads\//}
          echo GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED}
          GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED//\//-}
          echo GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED}
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_CLEANED}}"
          echo "branch_name=${BRANCH}"
          echo "branch_name=${BRANCH}" >> "$GITHUB_OUTPUT"

  build-chromatic-for-this-pr:
    name: Build Chromatic for PR
    runs-on: ubuntu-latest
    needs: [get-pr-num]        
    steps:
    - name: Debugging output
      run: |
        echo "pr_number=${{needs.get-pr-num.outputs.pr_number}}"
        echo "branch_name=${{needs.get-pr-num.outputs.branch_name}}"

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.get-pr-num.outputs.branch_name }}
        fetch-depth: 0
        token: ${{ github.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version-file: './frontend/package.json'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
  
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Run Chromatic
      id: run_chromatic
      uses: chromaui/action@latest
      with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
    - name: Echo output
      run: |
          echo "Chromatic URL: ${{ steps.run_chromatic.outputs.url }}"
          echo "Chromatic build ID: ${{ steps.run_chromatic.outputs.storybookUrl }}"
    - name: Build redirect file
      working-directory: frontend
      run: | # Create a redirect file to redirect to the storybook online
          mkdir -p chromatic_static_${{ needs.get-pr-num.outputs.pr_number }}
          echo "<meta http-equiv=refresh content=0;url=${{steps.run_chromatic.outputs.storybookUrl}}>" > chromatic_static_${{ needs.get-pr-num.outputs.pr_number }}/index.html
          echo "<meta http-equiv=refresh content=0;url=${{steps.run_chromatic.outputs.url}}>" > chromatic_static_${{ needs.get-pr-num.outputs.pr_number }}/build.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: frontend/chromatic_static_${{ needs.get-pr-num.outputs.pr_number }} # The folder that the build-chromatic script generates files.
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: prs/${{ needs.get-pr-num.outputs.pr_number }}/chromatic # The folder that we serve our chromatic files from 
  
  
 